### ISSUE TITLE
npm ERR! Invalid name: "playwright@latest" when running "Install Playwright" from VSCode Command

### ISSUE THREAD

**Issue by BW-PA** [microsoft/playwright-vscode#220] opened 2022-08-17 03:32 UTC
I wanted to try Playwright out.  Haven't previously had it installed anywhere.  Created a new folder for it in VSCode and installed the Playwright Extension v0.2.8

Opened up the command palette and ran "Test: Install Playwright"
Selected all browsers and included GitHub actions too.

Terminal output showing error is as follows

```
C:\...\MS Playwright Testing Utility> npm init --yes playwright@latest -- --quiet --browser=chromium --browser=firefox --browser=webkit --gha
npx: installed 1 in 1.798s
Getting started with writing end-to-end tests with Playwright:
Initializing project in 'playwright@latest'
Initializing NPM project (npm init -y)…    
npm ERR! Invalid name: "playwright@latest"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bwesl\AppData\Roaming\npm-cache\_logs\2022-08-17T03_29_03_729Z-debug.log
{ Error: Command failed: npm init -y
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at executeCommands (C:\Users\bwesl\AppData\Roaming\npm-cache\_npx\23664\node_modules\create-playwright\lib\index.js:4519:39)
    at Generator.run (C:\Users\bwesl\AppData\Roaming\npm-cache\_npx\23664\node_modules\create-playwright\lib\index.js:4592:5)   
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9228,
  stdout: null,
  stderr: null }
```

**Comment by BW-PA** [comment] 2022-08-17 03:33
Same issue also logged on the Playwright github repo too [https://github.com/microsoft/playwright/issues/16583#issue-1340626229](url)

**Comment by mxschmitt** [comment] 2022-08-17 07:29
Whats your npm version?

npm —version

**Comment by BW-PA** [comment] 2022-08-17 12:21
npm --version
6.4.1

**Comment by BW-PA** [comment] 2022-08-17 12:36
I just updated node.js and npm and npm --version now returns 8.17.0

`
npm --version
8.17.0
`
"Test: Install Playwright" command in VS Code now completes successfully

**Comment by AlexKomanov** [comment] 2022-08-17 13:24
So looks like the issue is related to the npm version?

**Comment by mxschmitt** [comment] 2022-08-17 13:27
We have a fix to make it work on NPM 6, so lets keep it open until its merged!

**Comment by AlexKomanov** [comment] 2022-08-17 13:28
Thanks @BW-PA @mxschmitt

**Closed** 2022-08-17 14:45 UTC
