### ISSUE TITLE
Overly eager in detecting Spec files

### ISSUE THREAD

**Issue by humbienri** [microsoft/playwright-vscode#34] opened 2021-08-24 15:10 UTC
Extension is detecting files that are NOT spec-containing files such as Page Object and/or Config modules.

Expectation is that spec detection should only detect (and show) modules that contains specs.

<img width="234" alt="PlaywrightTestExtension_DetectingNonSpecs" src="https://user-images.githubusercontent.com/1178569/130642148-6a1796dc-a2a2-4540-9cc2-4163d08039c7.png">

**Comment by mxschmitt** [comment] 2021-08-24 16:28
Hi, thanks for reporting the bug, this is a duplicate of #31.

**Closed by mxschmitt** 2021-08-24 16:28 UTC
