### ISSUE TITLE
Nothing happens when attempting to run test

### ISSUE THREAD

**Issue by benmccann** [microsoft/playwright-vscode#160] opened 2022-05-03 15:05 UTC
I click the play button which has a tooltip stating "Run Test" and nothing happens. I assume it's not running the test, but if it is then there is no visual feedback given.

![Screenshot from 2022-05-03 08-02-07](https://user-images.githubusercontent.com/322311/166479887-46f388fb-2079-4ea3-a506-513a8dbd699b.png)

This is the SvelteKit repository https://github.com/sveltejs/kit. The particular file I have open is `packages/kit/test/apps/basics/test/test.js`.

I'm using v0.2.3

**Comment by MatejBransky** [comment] 2022-05-04 07:38
I've started to have the same problem. 🤔

**Comment by pavelfeldman** [comment] 2022-05-16 03:40
Most likely you have more than one Playwright config. Use the drop down next to Test and debug actions in the toolbar to select your default configuration.

**Comment by MatejBransky** [comment] 2022-05-16 09:22
I can confirm that the issue was with multiple PW configs in our monorepo. Thank you @pavelfeldman ! 🙏

**Comment by benmccann** [comment] 2022-05-16 16:35
Yes, that was the issue. Thank you. I also see now that I can choose "Execute Using Profile..." to choose a config as well.

My repository is also monorepo with multiple projects in it. It would be nice if it could use the nearest Playwright config by default. I.e. just walk up the tree looking for a `playwright.config.js`

**Comment by craigjennings11** [comment] 2022-05-20 20:45
This is also problematic with the new component testing feature, since it's now encouraged to have a `playwright.config.js` and a `playwright-ct.config.js` file in your repo to run different tests with different configs.

**Comment by mxschmitt** [comment] 2022-07-06 09:31
Closing as per above: https://github.com/microsoft/playwright-vscode/issues/160#issuecomment-1127182561

**Closed by mxschmitt** 2022-07-06 09:31 UTC
Labels: triaging
